apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: quarkus-rhdh-1
  janus-idp.io/tekton: quarkus-rhdh-1
  backstage.io/kubernetes-id: quarkus-rhdh-1
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: quarkus-rhdh-1
resources:
  - application-dev.yaml